trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
- name: deployment_template_path
  value: $(Build.Repository.LocalPath)/azuredeploybarebones.json
- name: get_local
  value: Linked artifact

steps:
- checkout: self

- script: |
    echo 'Demonstrate issues finding a local file when running AzureResourceManagerTemplateDeployment@3 task.' && \
    echo 'First show that file is present. File contents for file at $(deployment_template_path).' && \
    ls && \
    echo '<--- file contents below --->' && \
    cat $(deployment_template_path) && \
    echo '<--- end of file contents --->'
  displayName: Output file state info

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '6d1de2e7-fc0b-4751-a617-94abc1ba9c80'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureCITest-Public'
    location: 'West US'
    templateLocation: '$(get_local)'
    csmFileLink: '$(deployment_template_path)'
    overrideParameters: '' #'-projectName armtestp'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'